name: test
on: push

jobs:
  test-all:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.4, 2.5, 2.6, 2.7, 3.0]

    steps:
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1.63.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - run: bundle exec rake test:unit test:remote
